version: '3'
services:

#Docker toolbox is used, project directory is mapped to shared folder /applyIt/

  #PHP Service
  app:
    image: php:fpm-alpine
    container_name: app
    tty: true
    volumes:
      - /applyIt/:/var/www/laravel/
    entrypoint:
      - php-fpm
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
#    volumes_from:
#      - app
    volumes:
      - /applyIt/:/var/www/laravel/
      - /applyIt/nginx/:/etc/nginx/conf.d/
#    links:
#      - app
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  mysql:
#    revert to older version because newer ones changed password encryption type that doesn't work with laravel out of the box
    image: mysql:5.7.26
    container_name: edgars-database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: apply
      MYSQL_ROOT_PASSWORD: edgars-secret-pw
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge
